{% set name = "ncvis-climate" %}
{% set version = "2023.08.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SEATStandards/ncvis/archive/refs/tags/{{ version }}.tar.gz
  sha256: 706529b7d5122eb1713ae03ae91e57ae458a9d5b4cba15afd15b4ff1b3f9d107
  patches:
    - patches/fix-resources-path.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - libnetcdf
    - wxwidgets
    - xorg-libxxf86vm   # [linux]

test:
  commands:
    - test -f ${PREFIX}/bin/ncvis
    - test -f ${PREFIX}/share/ncvis/resources/ne_110m_admin_0_countries.shp

about:
  home: https://github.com/SEATStandards/ncvis
  summary: NetCDF File Viewer
  description: NetCDF Visualizer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/SEATStandards/ncvis
  dev_url: https://github.com/SEATStandards/ncvis

extra:
  recipe-maintainers:
    - mahf708
    - xylar
