{% set name = "ncvis-climate" %}
{% set version = "2022.08.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SEATStandards/ncvis/archive/refs/tags/{{ version }}.tar.gz
  sha256: a522926739b2a05ef0b436fe67a2014557f9e5fecf3b7d7700964e9006a4bf3e
  patches:
    - patches/fix-resources-path.patch

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - libnetcdf
    - make
    - {{ compiler('cxx') }}
  host:
    - libnetcdf
    - wxwidgets
    - xorg-libxxf86vm
  run:

test:
  commands:
    - test -f ${PREFIX}/bin/ncvis
    - test -f ${PREFIX}/share/ncvis/resources/ne_110m_admin_0_countries.shp

about:
  home: https://github.com/SEATStandards/ncvis
  summary: 'NetCDF File Viewer'
  description: 'NetCDF Visualizer'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/SEATStandards/ncvis
  dev_url: https://github.com/SEATStandards/ncvis

extra:
  recipe-maintainers:
    - mahf708
    - xylar
