schema_version: 1

context:
  name: ncvis-climate
  version: "2026.10.07"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/SEATStandards/ncvis/archive/refs/tags/${{ version }}.tar.gz
  sha256: df6ccefe04ac0c822617db5e3e38e0a3f230f940061567679e7c3c956d8e1b23
  patches:
    - patches/fix-resources-path.patch

build:
  number: 0
  skip: win

requirements:
  build:
    - make
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - if: linux
      then: xorg-libxxf86vm
    - wxwidgets
    - libnetcdf

tests:
  - script:
      - test -f ${PREFIX}/bin/ncvis
      - test -f ${PREFIX}/share/ncvis/resources/ne_110m_admin_0_countries.shp

about:
  summary: NetCDF File Viewer
  description: NetCDF Visualizer
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/SEATStandards/ncvis
  repository: https://github.com/SEATStandards/ncvis
  documentation: https://github.com/SEATStandards/ncvis

extra:
  recipe-maintainers:
    - mahf708
    - xylar
